export const profile = {
  name: "Amit Mahida",
  role: "Senior Full Stack Architect | Frontend Architecture Leader | SaaS Platform Engineering",
  location: "Vadodara, Gujarat, India",
  phone: "+91 89057 21492",
  email: "amit.mahida9292@gmail.com",
  linkedin: "https://www.linkedin.com/in/amit-mahida",
  portfolio: "https://amitmahida.dev",
  pdf: `${import.meta.env.BASE_URL}Amit_Mahida_FullStack_Architect.pdf`,
  image: `${import.meta.env.BASE_URL}amit-mahida-profile.jpeg`,
  summary:
    "Senior Full Stack Architect and Engineering Leader with 11+ years designing, modernizing, and delivering enterprise web applications, multi-tenant SaaS platforms, and scalable frontend/backend systems. I own architecture decisions, lead engineering teams, improve scalability, mentor developers, and partner with product, UX, backend, and customer stakeholders to deliver business-critical platforms.",
  stack: [
    "React",
    "Angular",
    "Angular 17+",
    "TypeScript",
    "JavaScript",
    "RxJS",
    "Node.js",
    "Java",
    "Spring Boot",
    "AWS",
    "EC2",
    "S3",
    "CloudFront",
    "IAM",
    "EFS",
    "Elastic Beanstalk",
    "Amplify",
    "Route 53",
    "gRPC",
    "REST APIs",
    "GraphQL",
    "Kubernetes",
    "Docker",
    "Kafka",
    "CI/CD",
    "Nx",
    "NgRx",
    "Tailwind CSS",
    "PWA",
    "Ionic",
    "Material UI",
    "PrimeNG",
    "Bootstrap",
    "IndexedDB",
    "Redis",
    "MongoDB",
    "PostgreSQL",
    "DynamoDB",
    "Auth0",
    "Keycloak",
    "HashiCorp Vault",
    "AI-assisted Development",
    "ChatGPT",
    "GitHub Copilot",
    "CodeRabbit",
  ],
};

export const platformFlow = [
  {
    key: "client",
    stage: "Client UX",
    summary: "Horizontally scaled SPAs and product frontends",
    accent: "client",
    technologies: [
      { name: "Angular", logo: "angular" },
      { name: "React", logo: "react" },
      { name: "Ionic", logo: "ionic" },
      { name: "PWA", logo: "pwa" },
    ],
  },
  {
    key: "state",
    stage: "State & Caching",
    summary: "Offline-ready client storage plus server-side cache acceleration",
    accent: "state",
    technologies: [
      { name: "IndexedDB", logo: "indexeddb" },
      { name: "localStorage", logo: "localstorage" },
      { name: "sessionStorage", logo: "sessionstorage" },
      { name: "Redis", logo: "redis" },
    ],
  },
  {
    key: "ui",
    stage: "Mobile & UI System",
    summary: "Mobile-first controls and rich web component systems",
    accent: "ui",
    technologies: [
      { name: "Ionic", logo: "ionic" },
      { name: "Material UI", logo: "mui" },
      { name: "PrimeNG", logo: "primeng" },
      { name: "Bootstrap", logo: "bootstrap" },
    ],
  },
  {
    key: "edge",
    stage: "Edge Hosting",
    summary: "Static delivery, CDN caching, preview branches",
    accent: "edge",
    technologies: [
      { name: "S3", logo: "s3" },
      { name: "CloudFront", logo: "cloudfront" },
      { name: "Amplify", logo: "amplify" },
    ],
  },
  {
    key: "contracts",
    stage: "Client / Server",
    summary: "Typed and contract-led communication paths",
    accent: "contracts",
    technologies: [
      { name: "gRPC", logo: "grpc" },
      { name: "REST", logo: "rest" },
      { name: "GraphQL", logo: "graphql" },
    ],
  },
  {
    key: "services",
    stage: "Services & Data",
    summary: "Polyglot APIs backed by operational data stores",
    accent: "services",
    technologies: [
      { name: "Java", logo: "java" },
      { name: "Node.js", logo: "node" },
      { name: "Redis", logo: "redis" },
      { name: "MongoDB", logo: "mongo" },
      { name: "Postgres", logo: "postgres" },
      { name: "MySQL", logo: "mysql" },
      { name: "Firebase", logo: "firebase" },
      { name: "Supabase", logo: "supabase" },
      { name: "DynamoDB", logo: "dynamo" },
    ],
  },
  {
    key: "infra",
    stage: "Microservice Infra",
    summary: "Containerized services managed at scale",
    accent: "infra",
    technologies: [
      { name: "K8s", logo: "k8s" },
      { name: "Docker", logo: "docker" },
    ],
  },
  {
    key: "async",
    stage: "Async Workloads",
    summary: "Non-critical tasks handled through event queues",
    accent: "async",
    technologies: [
      { name: "Kafka", logo: "kafka" },
      { name: "SNS", logo: "sns" },
      { name: "SQS", logo: "sqs" },
    ],
  },
  {
    key: "security",
    stage: "Identity & Secrets",
    summary: "OAuth, enterprise SSO, and sensitive app metadata",
    accent: "security",
    technologies: [
      { name: "OAuth flows", logo: "oauth" },
      { name: "Auth0", logo: "auth0" },
      { name: "Keycloak", logo: "keycloak" },
      { name: "HashiCorp Vault APIs", logo: "vault" },
    ],
  },
  {
    key: "quality",
    stage: "Quality & Delivery",
    summary: "CI/CD, FE automation, and BE unit coverage",
    accent: "quality",
    technologies: [
      { name: "Jenkins", logo: "jenkins" },
      { name: "GitHub Actions", logo: "githubactions" },
      { name: "Jest", logo: "jest" },
      { name: "Karma", logo: "karma" },
      { name: "Jasmine", logo: "jasmine" },
      { name: "Cypress", logo: "cypress" },
      { name: "JUnit", logo: "junit" },
      { name: "Mockito", logo: "mockito" },
    ],
  },
];

export const metrics = [
  {
    value: 100,
    suffix: "+",
    label: "SaaS tenants",
    detail: "Owned architecture and delivery across a multi-tenant SaaS platform serving 100+ tenants.",
  },
  {
    value: 12,
    suffix: "+",
    label: "Shared UI libraries",
    detail: "Architected an Nx monorepo with reusable UI libraries and product components.",
  },
  {
    value: 80,
    suffix: "%",
    label: "Less automation effort",
    detail: "Schema-driven workflow automation reduced implementation effort by roughly 60-80%.",
  },
  {
    value: 4,
    suffix: "x",
    label: "Faster large-list UX",
    detail: "Task views supporting 3K+ records improved responsiveness by approximately 2-4x.",
  },
];

export const showcase = [
  {
    title: "Multi-Tenant SaaS Foundation",
    eyebrow: "Architecture ownership",
    stat: "100+ tenants",
    body:
      "Owned architecture and delivery across task management, dashboards, collaboration, analytics, workflow automation, timeline, and Gantt modules.",
    tags: ["Angular", "React", "Nx", "Multi-tenant SaaS"],
  },
  {
    title: "Workflow Automation Builder",
    eyebrow: "Schema-first product UX",
    stat: "60-80% faster",
    body:
      "Designed drag-and-drop Trigger-Condition-Action patterns with dynamic forms, reusable configurators, and reliable schema serialization.",
    tags: ["Workflow Automation", "Dynamic forms", "JSON"],
  },
  {
    title: "Heavy Board Performance",
    eyebrow: "Data at speed",
    stat: "2-4x faster",
    body:
      "Optimized 3K+ record task views with virtual scrolling, viewport rendering, DOM optimization, state decoupling, and tuned NgRx selectors.",
    tags: ["Virtual Scrolling", "NgRx", "Performance", "Caching"],
  },
  {
    title: "Cloud-Native Delivery",
    eyebrow: "Platform reliability",
    stat: "99.9% uptime",
    body:
      "Managed AWS deployments across EC2, S3, CloudFront, Route 53, Amplify, and RDS while improving scalability and serverless efficiency.",
    tags: ["AWS", "CloudFront", "Route 53", "CI/CD"],
  },
];

export const experience = [
  {
    role: "SDE 3 / Senior Full Stack Architect",
    company: "Rishabh Software",
    place: "Vadodara, India",
    period: "February 2025 - Present",
    accent: "mint",
    highlights: [
      "Own frontend architecture and delivery for a multi-tenant SaaS platform serving 100+ tenants across Task Management, Dashboards, Collaboration, Analytics, Workflow Automation, Timeline, and Gantt modules.",
      "Architected an Nx monorepo with 12+ shared UI libraries and reusable components, reducing duplicate implementation and accelerating feature delivery across product modules.",
      "Designed a schema-driven drag-and-drop Workflow Automation Builder using Trigger-Condition-Action patterns, enabling new automation types through configuration-first development and reducing implementation effort by approximately 60-80%.",
      "Built dynamic forms, reusable configurators, and reliable schema serialization/deserialization workflows, improving automation publishing accuracy and reducing workflow configuration issues.",
      "Optimized data-heavy task views supporting 3K+ records per list through virtual scrolling, viewport-based rendering, DOM optimization, and state decoupling, improving large-list responsiveness by approximately 2-4x.",
      "Improved asset-heavy screen performance through image caching and optimization strategies, reducing perceived load time for repeated navigation by approximately 30-50%.",
      "Tuned NgRx state management through selector optimization, state normalization, and reduced rerender patterns, improving dashboard and board stability under heavy data loads.",
      "Integrated Java REST APIs through Swagger/OpenAPI contracts, supported PostgreSQL-backed reporting/filtering flows, and implemented Mixpanel instrumentation for product analytics and funnel visibility.",
    ],
  },
  {
    role: "Technical Lead",
    company: "Innovecture",
    place: "Remote",
    period: "August 2024 - January 2025",
    accent: "coral",
    highlights: [
      "Led technical delivery for Angular, React, Node.js, and AWS-based application initiatives, balancing feature delivery, infrastructure improvements, and scalability goals.",
      "Partnered on a two-year technology roadmap, aligning engineering priorities with product strategy, modernization opportunities, and platform growth needs.",
      "Mentored junior engineers through code reviews, architecture discussions, implementation guidance, and delivery planning.",
      "Prototyped data-processing and integration capabilities to validate feasibility before committing engineering capacity to production implementation.",
      "Assessed system load patterns and delivered Angular/Node.js optimization plans that improved performance and scalability by approximately 25%.",
      "Modernized AWS-based infrastructure and product features in collaboration with product teams, contributing to a reported 30% increase in user engagement.",
      "Managed customer-facing progress discussions, feedback loops, and issue resolution, supporting 95% client satisfaction and repeat business.",
      "Improved GitHub-based collaboration practices, reducing merge conflicts by approximately 40% and strengthening code review effectiveness.",
      "Used Jira and Confluence to improve planning visibility, delivery tracking, and documentation quality, reducing delivery timelines by approximately 20%.",
      "Developed scalable Node.js backend solutions and integrated AWS Lambda functions to improve serverless architecture efficiency and reduce operational costs by approximately 25%.",
      "Managed AWS deployments across EC2, S3, CloudFront, Route 53, Amplify, and RDS, supporting 99.9% uptime targets and improved scalability.",
    ],
  },
  {
    role: "Frontend Development Head",
    company: "It's All Savvy",
    place: "London, United Kingdom / Remote",
    period: "September 2021 - July 2024",
    accent: "violet",
    highlights: [
      "Led frontend engineering for product-facing web applications, partnering with product managers, UX/UI designers, and backend teams across Scrum and Kanban delivery models.",
      "Drove frontend architecture, implementation standards, and delivery execution that contributed to 2x revenue growth over two years.",
      "Established code quality practices using Jasmine, Karma, code reviews, and frontend engineering standards, reducing production bugs by approximately 40%.",
      "Improved application speed and scalability through lazy loading, caching, code splitting, and performance-focused data handling, reducing load times by approximately 35%.",
      "Integrated frontend applications with Node.js, Java, and REST API services, improving data flow and transaction speed by approximately 25% on a high-traffic platform.",
      "Guided frontend delivery priorities, implementation decisions, and team execution to improve user experience, maintainability, and release confidence.",
    ],
  },
  {
    role: "Development Team Lead",
    company: "Rishabh Software",
    place: "Vadodara, Gujarat, India",
    period: "April 2021 - September 2021",
    accent: "gold",
    highlights: [
      "Led Agile delivery across sprint planning, daily standups, retrospectives, and continuous improvement practices, improving project efficiency by approximately 30% and reducing delivery time by approximately 20%.",
      "Delivered responsive web applications across desktop and mobile experiences, improving mobile traffic by approximately 50%.",
      "Managed React, Angular, and Spring Boot implementation efforts, coordinating product features, testing, integration, and deployment activities.",
      "Improved release quality through GitHub workflows, testing discipline, and deployment coordination, reducing deployment errors by approximately 30%.",
      "Introduced Ionic-based cross-platform mobile development, improving user engagement by approximately 25% through integrated web and mobile experiences.",
      "Led delivery of e-commerce and internal dashboard projects, improving team productivity and project execution speed by approximately 25%.",
      "Applied modern Angular practices and frontend optimization techniques, improving application performance by approximately 15%.",
    ],
  },
  {
    role: "Senior Software Engineer",
    company: "Rishabh Software",
    place: "Vadodara, India",
    period: "April 2019 - May 2021",
    accent: "blue",
    highlights: [
      "Migrated legacy AngularJS applications to modern Angular, improving performance by approximately 30% while increasing maintainability through component-based architecture and modular code structure.",
      "Collaborated with project managers and engineering teams to define implementation objectives, coding standards, and review practices, improving code quality by approximately 20%.",
      "Refactored legacy codebases to reduce maintenance effort, improve functionality, and increase long-term extensibility.",
      "Introduced automated testing, CI practices, and improved code review techniques, increasing development productivity by approximately 20%.",
      "Applied Agile delivery practices across sprint planning, standups, and retrospectives, improving collaboration and reducing delivery timelines by approximately 15%.",
    ],
  },
  {
    role: "Software Engineer",
    company: "Rishabh Software",
    place: "Vadodara, India",
    period: "January 2015 - March 2019",
    accent: "mint",
    highlights: [
      "Built and enhanced enterprise business applications with internationalization support, modern UI improvements, comprehensive testing, and code coverage practices.",
      "Delivered Angular upgrades, custom application features, REST API integrations, cloud infrastructure setup, compression techniques, Power BI visuals, and technology roadmap inputs, improving system performance by approximately 25%.",
      "Strengthened team and stakeholder communication through regular updates, documentation, Jira, and Confluence, reducing delivery errors by approximately 20%.",
      "Analyzed user feedback and market trends to inform feature improvements, increasing user satisfaction by approximately 15%.",
    ],
  },
];

export const skillGroups = [
  {
    name: "Frontend",
    skills: [
      "Angular",
      "Angular 17+",
      "React",
      "Nx Monorepo",
      "RxJS",
      "NgRx",
      "Ionic",
      "PWA",
      "IndexedDB",
      "localStorage",
      "sessionStorage",
      "JavaScript",
      "TypeScript",
      "Next.js",
      "HTML5",
      "CSS3",
      "Tailwind",
      "Material UI",
      "PrimeNG",
      "Bootstrap",
      "Responsive Web Design",
      "Virtual Scrolling",
      "Frontend Performance Optimization",
      "UX Design",
    ],
  },
  {
    name: "Backend",
    skills: [
      "Node.js",
      "NestJS",
      "Java",
      "J2EE",
      "Spring Boot",
      "Tomcat",
      "Nginx",
      "Redis",
      "REST APIs",
      "gRPC",
      "GraphQL",
      "OpenAPI",
      "Swagger UI",
      "API Design",
      "Microservices",
    ],
  },
  {
    name: "Cloud & Edge",
    skills: ["AWS", "AWS EC2", "S3", "CloudFront", "Amplify", "IAM", "EFS", "Elastic Beanstalk", "Route53", "DynamoDB"],
  },
  {
    name: "Data",
    skills: ["PostgreSQL", "MongoDB", "MySQL", "Firebase", "Supabase", "DynamoDB", "Enterprise SaaS", "Multi-tenant Architecture", "Distributed Systems", "Scalable Web Applications", "MEAN Stack", "MERN Stack"],
  },
  {
    name: "Caching & State",
    skills: ["Redis", "IndexedDB", "localStorage", "sessionStorage", "NgRx", "PWA", "Service Workers"],
  },
  {
    name: "Platform Infra",
    skills: [
      "Kubernetes",
      "K8s",
      "Docker",
      "Kafka",
      "AWS SNS",
      "AWS SQS",
      "Microservices",
      "HashiCorp Vault",
      "Vault APIs",
    ],
  },
  {
    name: "Identity & Integrations",
    skills: [
      "OAuth flows",
      "Auth0",
      "Keycloak",
      "RBAC",
      "Slack",
      "Microsoft Teams",
      "Google Drive",
      "OneDrive",
      "HubSpot",
      "Pipedrive",
      "GitHub",
      "GitLab",
    ],
  },
  {
    name: "CI/CD & Testing",
    skills: ["Jenkins", "GitHub Actions", "CI/CD", "Jest", "Karma", "Jasmine", "Cypress", "JUnit", "Mockito"],
  },
  {
    name: "Leadership",
    skills: ["Engineering Leadership", "Solution Architecture", "System Design", "Technical Roadmaps", "Team Leadership", "Mentoring", "Agile/Scrum", "SDLC", "Release Planning", "Stakeholder Management", "Collaboration", "Problem Solving"],
  },
  {
    name: "AI & Delivery",
    skills: ["AI-assisted Development", "ChatGPT", "ChatGPT Integration", "GitHub Copilot", "Claude Code", "Codex", "Replit", "CodeRabbit", "Workflow Automation", "Jira", "Confluence", "Git"],
  },
];

export const education = [
  {
    degree: "Master's Degree in Master of Computer Applications - MCA",
    school: "ISTAR College - Gujarat Technological University",
    place: "Gujarat, India",
    year: "December 2015",
  },
  {
    degree: "Bachelor's Degree in Computer Science",
    school: "N V Patel College of Pure & Applied Sciences",
    place: "Gujarat, India",
    year: "December 2012",
  },
];
