export const profile = {
  name: "Amit Mahida",
  role: "AI-Powered Full Stack Architect | Angular, React, Node.js, Spring Boot, AWS, Kubernetes | B2B SaaS, Microservices & Cloud-Native Systems | 12+ Years",
  location: "Vadodara, Gujarat, India",
  phone: "+91 8905721492",
  email: "amit.mahida9292@gmail.com",
  linkedin: "https://www.linkedin.com/in/amit-mahida",
  portfolio: "https://bold.pro/my/amit-mahida-250107142551/213r",
  pdf: `${import.meta.env.BASE_URL}Amit_Mahida_FE_Architect.pdf`,
  image: `${import.meta.env.BASE_URL}amit-mahida-profile.jpeg`,
  summary:
    "AI-powered full-stack architecture leader with deep React, Angular, Node.js, Spring Boot, AWS, Kubernetes, and data-heavy product experience. I build scalable SaaS interfaces, schema-driven builders, cloud-native systems, and high-performing teams that ship dependable product platforms.",
  stack: [
    "React",
    "Angular",
    "TypeScript",
    "Node.js",
    "Java",
    "AWS",
    "S3",
    "CloudFront",
    "Amplify",
    "gRPC",
    "GraphQL",
    "Kubernetes",
    "Docker",
    "Kafka",
    "Nx",
    "NgRx",
    "PWA",
    "Ionic",
    "Material UI",
    "PrimeNG",
    "Bootstrap",
    "IndexedDB",
    "Redis",
    "MongoDB",
    "PostgreSQL",
    "DynamoDB",
    "Auth0",
    "Keycloak",
    "HashiCorp Vault",
  ],
};

export const platformFlow = [
  {
    key: "client",
    stage: "Client UX",
    summary: "Horizontally scaled SPAs and product frontends",
    accent: "client",
    technologies: [
      { name: "Angular", logo: "angular" },
      { name: "React", logo: "react" },
      { name: "Ionic", logo: "ionic" },
      { name: "PWA", logo: "pwa" },
    ],
  },
  {
    key: "state",
    stage: "State & Caching",
    summary: "Offline-ready client storage plus server-side cache acceleration",
    accent: "state",
    technologies: [
      { name: "IndexedDB", logo: "indexeddb" },
      { name: "localStorage", logo: "localstorage" },
      { name: "sessionStorage", logo: "sessionstorage" },
      { name: "Redis", logo: "redis" },
    ],
  },
  {
    key: "ui",
    stage: "Mobile & UI System",
    summary: "Mobile-first controls and rich web component systems",
    accent: "ui",
    technologies: [
      { name: "Ionic", logo: "ionic" },
      { name: "Material UI", logo: "mui" },
      { name: "PrimeNG", logo: "primeng" },
      { name: "Bootstrap", logo: "bootstrap" },
    ],
  },
  {
    key: "edge",
    stage: "Edge Hosting",
    summary: "Static delivery, CDN caching, preview branches",
    accent: "edge",
    technologies: [
      { name: "S3", logo: "s3" },
      { name: "CloudFront", logo: "cloudfront" },
      { name: "Amplify", logo: "amplify" },
    ],
  },
  {
    key: "contracts",
    stage: "Client / Server",
    summary: "Typed and contract-led communication paths",
    accent: "contracts",
    technologies: [
      { name: "gRPC", logo: "grpc" },
      { name: "REST", logo: "rest" },
      { name: "GraphQL", logo: "graphql" },
    ],
  },
  {
    key: "services",
    stage: "Services & Data",
    summary: "Polyglot APIs backed by operational data stores",
    accent: "services",
    technologies: [
      { name: "Java", logo: "java" },
      { name: "Node.js", logo: "node" },
      { name: "Redis", logo: "redis" },
      { name: "MongoDB", logo: "mongo" },
      { name: "Postgres", logo: "postgres" },
      { name: "MySQL", logo: "mysql" },
      { name: "Firebase", logo: "firebase" },
      { name: "Supabase", logo: "supabase" },
      { name: "DynamoDB", logo: "dynamo" },
    ],
  },
  {
    key: "infra",
    stage: "Microservice Infra",
    summary: "Containerized services managed at scale",
    accent: "infra",
    technologies: [
      { name: "K8s", logo: "k8s" },
      { name: "Docker", logo: "docker" },
    ],
  },
  {
    key: "async",
    stage: "Async Workloads",
    summary: "Non-critical tasks handled through event queues",
    accent: "async",
    technologies: [
      { name: "Kafka", logo: "kafka" },
      { name: "SNS", logo: "sns" },
      { name: "SQS", logo: "sqs" },
    ],
  },
  {
    key: "security",
    stage: "Identity & Secrets",
    summary: "OAuth, enterprise SSO, and sensitive app metadata",
    accent: "security",
    technologies: [
      { name: "OAuth flows", logo: "oauth" },
      { name: "Auth0", logo: "auth0" },
      { name: "Keycloak", logo: "keycloak" },
      { name: "HashiCorp Vault APIs", logo: "vault" },
    ],
  },
  {
    key: "quality",
    stage: "Quality & Delivery",
    summary: "CI/CD, FE automation, and BE unit coverage",
    accent: "quality",
    technologies: [
      { name: "Jenkins", logo: "jenkins" },
      { name: "GitHub Actions", logo: "githubactions" },
      { name: "Jest", logo: "jest" },
      { name: "Karma", logo: "karma" },
      { name: "Jasmine", logo: "jasmine" },
      { name: "Cypress", logo: "cypress" },
      { name: "JUnit", logo: "junit" },
      { name: "Mockito", logo: "mockito" },
    ],
  },
];

export const metrics = [
  {
    value: 100,
    suffix: "+",
    label: "SaaS tenants",
    detail: "Owned frontend architecture for a multi-tenant SaaS platform.",
  },
  {
    value: 5000,
    suffix: "+",
    label: "Daily active users",
    detail: "Supported product workflows across task, dashboard, analytics, and automation modules.",
  },
  {
    value: 12,
    suffix: "+",
    label: "Shared UI libraries",
    detail: "Established an Nx monorepo to accelerate delivery across modules.",
  },
  {
    value: 80,
    suffix: "%",
    label: "Less automation effort",
    detail: "Schema-driven workflow builder cut new automation implementation effort by roughly 60-80%.",
  },
];

export const showcase = [
  {
    title: "Multi-Tenant SaaS Foundation",
    eyebrow: "Architecture ownership",
    stat: "100+ tenants",
    body:
      "Led frontend architecture and delivery across task management, dashboards, collaboration, analytics, timeline, and workflow automation.",
    tags: ["React", "Angular", "Nx", "Module federation mindset"],
  },
  {
    title: "Workflow Automation Builder",
    eyebrow: "Schema-first product UX",
    stat: "60-80% faster",
    body:
      "Designed drag-and-drop Trigger-Condition-Action flows with dynamic forms, reusable configurators, and reliable schema serialization.",
    tags: ["Drag and drop", "Config schemas", "Dynamic forms"],
  },
  {
    title: "Heavy Board Performance",
    eyebrow: "Data at speed",
    stat: "3K+ tasks",
    body:
      "Improved large-list task experiences with viewport rendering, DOM optimization, virtualization, image caching, and tuned state selectors.",
    tags: ["Virtualization", "NgRx", "Caching", "Rendering"],
  },
  {
    title: "Product Instrumentation",
    eyebrow: "Insightful systems",
    stat: "Funnel clarity",
    body:
      "Strengthened integrations with Java REST APIs, Swagger/OpenAPI, PostgreSQL reporting workflows, and Mixpanel tracking.",
    tags: ["OpenAPI", "PostgreSQL", "Mixpanel", "REST"],
  },
];

export const experience = [
  {
    role: "SDE 3 - Product",
    company: "Rishabh Software",
    place: "Vadodara, Gujarat, India",
    period: "February 2025 - Present",
    accent: "mint",
    highlights: [
      "Led frontend architecture and delivery for a multi-tenant SaaS platform across Task Management, Dashboards, Workflow Automation, Collaboration, Analytics, Timeline, and Gantt modules.",
      "Established an Nx monorepo with 12+ shared UI and component libraries, reducing duplication and accelerating feature delivery across product modules.",
      "Architected a schema-driven drag-and-drop Workflow Automation Builder using Trigger -> Condition -> Action flows, enabling new automation types through configuration and schema changes.",
      "Designed reusable dynamic-form systems with schema serialization and deserialization pipelines, improving workflow reliability and reducing configuration complexity.",
      "Engineered high-performance task management experiences tested with 10K+ tasks using virtualization, viewport-based rendering, incremental loading, and DOM optimization.",
      "Improved frontend responsiveness on data-heavy screens with image optimization, caching, selective rendering, lazy loading, and NgRx state optimization.",
      "Delivered advanced Timeline and Gantt experiences with dependency management, zoom controls, viewport-based fetching, and optimized rendering strategies.",
      "Built and maintained integrations with Slack, Microsoft Teams, Google Drive, OneDrive, HubSpot, Pipedrive, GitHub, GitLab, Meta Ads, Google Ads, and LinkedIn.",
      "Integrated Angular frontend systems with Java REST APIs using Swagger/OpenAPI contracts, PostgreSQL-backed filtering and reporting workflows, and Mixpanel analytics instrumentation.",
      "Partnered with product, QA, backend, and leadership stakeholders on architecture decisions, release planning, frontend modernization, and platform performance initiatives.",
    ],
  },
  {
    role: "Technical Lead",
    company: "Innovecture",
    place: "Pune District, Maharashtra, India",
    period: "August 2024 - February 2025",
    accent: "coral",
    highlights: [
      "Led a cross-functional team delivering scalable full-stack applications with Angular, Node.js, and NestJS under tight delivery timelines.",
      "Mentored junior developers through code reviews, knowledge-sharing sessions, design-pattern guidance, and coding best practices.",
      "Collaborated with product managers and stakeholders to define technical requirements, shape system architecture, and keep delivery aligned with business goals.",
      "Designed and implemented dynamic, responsive Angular interfaces that improved usability, accessibility, and consistency across device sizes.",
      "Developed reusable components and modules with Nx to streamline frontend development and reduce time-to-market for new features.",
      "Engineered APIs and microservices with NestJS, improving scalability, maintainability, and service boundaries.",
      "Integrated Microsoft SQL Server, PostgreSQL, and MongoDB data stores while optimizing query and indexing strategies for a 15% application performance improvement.",
      "Implemented authentication and authorization patterns with RBAC and HashiCorp Vault for secure key and secrets management.",
      "Spearheaded Docker-based deployment adoption to reduce deployment time and improve environment consistency.",
      "Reduced development time by 25% through process improvements, debugging discipline, profiling, security audits, and streamlined monorepo management.",
    ],
  },
  {
    role: "Full Stack Developer",
    company: "It's All Savvy",
    place: "London, England, United Kingdom",
    period: "September 2021 - June 2024",
    accent: "violet",
    highlights: [
      "Directed technical delivery across Angular, React, Java, MongoDB, and AWS projects, improving software reliability and reducing post-deployment issues by 30%.",
      "Implemented testing practices with Karma, Jasmine, and Cypress, reducing defects by 30% and raising confidence in release quality.",
      "Coordinated closely with stakeholders to keep milestones, budgets, and delivery expectations aligned, achieving a 95% on-time delivery rate.",
      "Mentored and led a development team of 6, increasing productivity by 20% while building a collaborative engineering culture.",
      "Managed AWS deployments and configuration optimization, reducing hosting costs by 25% while maintaining 99.9% uptime.",
      "Used Jira and Confluence to improve project visibility, documentation quality, and communication across technical and non-technical teams.",
      "Aligned engineering goals with strategic business objectives, supporting company growth and contributing to a 25% increase in project ROI.",
      "Worked in a startup environment that required hands-on contribution across development, design, marketing, customer support, and product problem-solving.",
      "Drove innovation and process improvements by staying current with industry trends, reducing development time by 15%.",
    ],
  },
  {
    role: "Development Team Lead",
    company: "Rishabh Software",
    place: "Vadodara, Gujarat, India",
    period: "April 2021 - September 2021",
    accent: "gold",
    highlights: [
      "Consulted with engineering team members to assess system load and develop improvement plans with Angular and Node.js, improving performance and scalability by 25%.",
      "Maintained complex technology infrastructure and delivered new product features with AWS services, contributing to a 30% increase in user engagement.",
      "Discussed project progress with customers, collected feedback across delivery stages, and addressed concerns promptly to support a 95% client satisfaction rate.",
      "Led version-control practices using GitHub and related repositories, reducing merge conflicts by 40% and improving collaboration efficiency.",
      "Managed Jira delivery workflows and Confluence documentation, improving tracking accuracy and reducing project delivery time by 20%.",
      "Collaborated with product teams on future product planning, driving innovation and contributing to a 15% increase in product revenue.",
      "Implemented Angular and React components that improved frontend interactivity and user experience, reducing bounce rates by 20%.",
      "Developed scalable Node.js backend solutions and integrated AWS Lambda functions to improve serverless architecture and reduce operational costs by 25%.",
      "Managed AWS deployments across EC2, S3, CloudFront, Route53, and RDS, supporting 99.9% uptime with improved scalability and performance.",
    ],
  },
  {
    role: "Senior Software Engineer",
    company: "Rishabh Software",
    place: "Vadodara Area, India",
    period: "April 2019 - May 2021",
    accent: "blue",
    highlights: [
      "Collaborated with project managers to select ambitious but realistic coding milestones for pre-release software development.",
      "Revised, modularized, and upgraded older code bases to modern development standards, reducing operating costs and improving functionality.",
      "Pioneered broader code-review practices that brought more engineering ideas into final product decisions.",
      "Participated in software field testing to validate on-site performance and production readiness.",
      "Worked in Agile delivery environments to maintain project timelines, prioritize effectively, and use available resources efficiently.",
      "Strengthened maintainability across legacy systems through refactoring, modularization, and practical quality gates.",
    ],
  },
  {
    role: "Software Engineer",
    company: "Rishabh Software",
    place: "Vadodara Area, India",
    period: "January 2015 - March 2019",
    accent: "mint",
    highlights: [
      "Designed and developed efficient software solutions tailored to clients' business objectives.",
      "Implemented internationalization and localization support for multilingual product experiences.",
      "Collaborated with web designers to create modern, user-friendly UI designs and improve customer-facing workflows.",
      "Conducted unit testing and browser-performance validation to strengthen reliability across supported environments.",
      "Configured environments for static code coverage analysis and improved quality visibility for delivery teams.",
      "Upgraded AngularJS applications to newer Angular versions while preserving business-critical behavior.",
      "Created RESTful APIs with Node.js and MongoDB, including MongoDB Atlas and MongoDB Stitch cloud deployment configuration.",
      "Developed Android and iOS builds using Apache Cordova for cross-platform mobile delivery.",
      "Applied code compression and performance techniques to improve load behavior and runtime efficiency.",
      "Designed custom Power BI visuals and explored map-based technologies for more innovative reporting and visualization use cases.",
    ],
  },
];

export const skillGroups = [
  {
    name: "Frontend",
    skills: [
      "Angular",
      "React",
      "Nx Monorepo",
      "NgRx",
      "Ionic",
      "PWA",
      "IndexedDB",
      "localStorage",
      "sessionStorage",
      "JavaScript",
      "TypeScript",
      "Next.js",
      "HTML5",
      "CSS3",
      "Tailwind",
      "Material UI",
      "PrimeNG",
      "Bootstrap",
      "Responsive Web Design",
      "UX Design",
    ],
  },
  {
    name: "Backend",
    skills: [
      "Node.js",
      "NestJS",
      "Java",
      "J2EE",
      "Spring Boot",
      "Tomcat",
      "Nginx",
      "Redis",
      "REST APIs",
      "gRPC",
      "GraphQL",
      "OpenAPI",
      "Swagger UI",
    ],
  },
  {
    name: "Cloud & Edge",
    skills: ["AWS EC2", "S3", "CloudFront", "Amplify", "IAM", "EFS", "Elastic Beanstalk", "Route53", "DynamoDB"],
  },
  {
    name: "Data",
    skills: ["MongoDB", "PostgreSQL", "MySQL", "Firebase", "Supabase", "DynamoDB", "MEAN Stack", "MERN Stack"],
  },
  {
    name: "Caching & State",
    skills: ["Redis", "IndexedDB", "localStorage", "sessionStorage", "NgRx", "PWA", "Service Workers"],
  },
  {
    name: "Platform Infra",
    skills: [
      "Kubernetes",
      "K8s",
      "Docker",
      "Kafka",
      "AWS SNS",
      "AWS SQS",
      "Microservices",
      "HashiCorp Vault",
      "Vault APIs",
    ],
  },
  {
    name: "Identity & Integrations",
    skills: [
      "OAuth flows",
      "Auth0",
      "Keycloak",
      "RBAC",
      "Slack",
      "Microsoft Teams",
      "Google Drive",
      "OneDrive",
      "HubSpot",
      "Pipedrive",
      "GitHub",
      "GitLab",
    ],
  },
  {
    name: "CI/CD & Testing",
    skills: ["Jenkins", "GitHub Actions", "CI/CD", "Jest", "Karma", "Jasmine", "Cypress", "JUnit", "Mockito"],
  },
  {
    name: "Leadership",
    skills: ["Solution Architecture", "API Design", "System Architecture", "Design Patterns", "Mentoring", "Team Leadership", "Collaboration", "Problem Solving"],
  },
  {
    name: "AI & Delivery",
    skills: ["ChatGPT Integration", "Claude Code", "Codex", "Replit", "Copilot", "CodeRabbit", "Jira", "Confluence", "Git"],
  },
];

export const education = [
  {
    degree: "Master's Degree in Master of Computer Applications - MCA",
    school: "ISTAR College - Gujarat Technological University",
    place: "Gujarat, India",
    year: "December 2015",
  },
  {
    degree: "Bachelor's Degree in Computer Science",
    school: "N V Patel College of Pure & Applied Sciences",
    place: "Gujarat, India",
    year: "December 2012",
  },
];
