const simpleIcon = (slug, fallback, title = fallback) => ({
  src: `https://cdn.simpleicons.org/${slug}?viewbox=auto`,
  fallback,
  title,
});

const awsIcon = (file, fallback, title = fallback) => ({
  src: `https://cdn.jsdelivr.net/npm/aws-icons@3.3.0/icons/architecture-service/${file}.svg`,
  fallback,
  title,
});

const externalIcon = (src, fallback, title = fallback) => ({
  src,
  fallback,
  title,
});

export const techLogos = {
  angular: simpleIcon("angular", "A", "Angular"),
  react: simpleIcon("react", "R", "React"),
  nx: simpleIcon("nx", "Nx", "Nx"),
  ngrx: simpleIcon("ngrx", "NgRx", "NgRx"),
  rxjs: simpleIcon("reactivex", "Rx", "RxJS"),
  ionic: simpleIcon("ionic", "Io", "Ionic"),
  pwa: simpleIcon("pwa", "PWA", "Progressive Web Apps"),
  indexeddb: simpleIcon("html5", "IDB", "IndexedDB"),
  localstorage: simpleIcon("html5", "LS", "localStorage"),
  sessionstorage: simpleIcon("html5", "SS", "sessionStorage"),
  javascript: simpleIcon("javascript", "JS", "JavaScript"),
  typescript: simpleIcon("typescript", "TS", "TypeScript"),
  nextjs: simpleIcon("nextdotjs", "N", "Next.js"),
  html5: simpleIcon("html5", "H5", "HTML5"),
  css3: simpleIcon("css", "CSS", "CSS3"),
  tailwind: simpleIcon("tailwindcss", "TW", "Tailwind CSS"),
  mui: simpleIcon("mui", "MUI", "Material UI"),
  primeng: simpleIcon("primeng", "PNG", "PrimeNG"),
  bootstrap: simpleIcon("bootstrap", "B", "Bootstrap"),
  figma: simpleIcon("figma", "Fg", "Figma"),
  node: simpleIcon("nodedotjs", "Node", "Node.js"),
  nestjs: simpleIcon("nestjs", "N", "NestJS"),
  java: simpleIcon("openjdk", "J", "Java"),
  springboot: simpleIcon("springboot", "SB", "Spring Boot"),
  tomcat: simpleIcon("apachetomcat", "TC", "Apache Tomcat"),
  nginx: simpleIcon("nginx", "Nx", "Nginx"),
  grpc: externalIcon("https://api.iconify.design/devicon/grpc.svg", "gRPC", "gRPC"),
  graphql: simpleIcon("graphql", "GQL", "GraphQL"),
  openapi: simpleIcon("openapiinitiative", "API", "OpenAPI"),
  swagger: simpleIcon("swagger", "Sw", "Swagger"),
  rest: awsIcon("AmazonAPIGateway", "REST", "REST APIs"),
  aws: externalIcon("https://api.iconify.design/logos:aws.svg", "AWS", "AWS"),
  ec2: awsIcon("AmazonEC2", "EC2", "Amazon EC2"),
  s3: awsIcon("AmazonSimpleStorageService", "S3", "Amazon S3"),
  cloudfront: awsIcon("AmazonCloudFront", "CF", "Amazon CloudFront"),
  amplify: awsIcon("AWSAmplify", "Amp", "AWS Amplify"),
  iam: awsIcon("AWSIdentityandAccessManagement", "IAM", "AWS IAM"),
  efs: awsIcon("AmazonEFS", "EFS", "Amazon EFS"),
  elasticbeanstalk: awsIcon("AWSElasticBeanstalk", "EB", "AWS Elastic Beanstalk"),
  route53: awsIcon("AmazonRoute53", "R53", "Amazon Route 53"),
  dynamo: awsIcon("AmazonDynamoDB", "DDB", "Amazon DynamoDB"),
  sns: awsIcon("AmazonSimpleNotificationService", "SNS", "Amazon SNS"),
  sqs: awsIcon("AmazonSimpleQueueService", "SQS", "Amazon SQS"),
  mongo: simpleIcon("mongodb", "MDB", "MongoDB"),
  postgres: simpleIcon("postgresql", "PG", "PostgreSQL"),
  mysql: simpleIcon("mysql", "SQL", "MySQL"),
  redis: simpleIcon("redis", "Re", "Redis"),
  firebase: simpleIcon("firebase", "Fb", "Firebase"),
  supabase: simpleIcon("supabase", "Sb", "Supabase"),
  kubernetes: simpleIcon("kubernetes", "K8s", "Kubernetes"),
  docker: simpleIcon("docker", "D", "Docker"),
  kafka: simpleIcon("apachekafka", "K", "Apache Kafka"),
  oauth: externalIcon("https://api.iconify.design/devicon/oauth.svg", "OA", "OAuth"),
  auth0: simpleIcon("auth0", "A0", "Auth0"),
  keycloak: simpleIcon("keycloak", "KC", "Keycloak"),
  vault: simpleIcon("vault", "V", "HashiCorp Vault"),
  jenkins: simpleIcon("jenkins", "J", "Jenkins"),
  githubactions: simpleIcon("githubactions", "GA", "GitHub Actions"),
  github: simpleIcon("github", "GH", "GitHub"),
  gitlab: simpleIcon("gitlab", "GL", "GitLab"),
  jest: simpleIcon("jest", "Jest", "Jest"),
  karma: externalIcon("https://api.iconify.design/devicon/karma.svg", "K", "Karma"),
  jasmine: simpleIcon("jasmine", "Js", "Jasmine"),
  cypress: simpleIcon("cypress", "Cy", "Cypress"),
  junit: simpleIcon("junit5", "JU", "JUnit"),
  mockito: externalIcon("https://upload.wikimedia.org/wikipedia/commons/2/2c/Mockito_Logo.png", "Mo", "Mockito"),
  slack: externalIcon("https://api.iconify.design/logos:slack-icon.svg", "Sl", "Slack"),
  teams: externalIcon("https://api.iconify.design/logos:microsoft-teams.svg", "Tm", "Microsoft Teams"),
  googledrive: simpleIcon("googledrive", "GD", "Google Drive"),
  onedrive: externalIcon("https://api.iconify.design/logos:microsoft-onedrive.svg", "OD", "OneDrive"),
  hubspot: simpleIcon("hubspot", "Hs", "HubSpot"),
  pipedrive: externalIcon("https://api.iconify.design/logos:pipedrive.svg", "Pd", "Pipedrive"),
  openai: externalIcon("https://api.iconify.design/simple-icons:openai.svg", "AI", "OpenAI"),
  claude: simpleIcon("claude", "Cl", "Claude"),
  codex: externalIcon("https://api.iconify.design/simple-icons:openai.svg", "Cx", "Codex"),
  replit: simpleIcon("replit", "Re", "Replit"),
  githubcopilot: simpleIcon("githubcopilot", "Co", "GitHub Copilot"),
  coderabbit: simpleIcon("coderabbit", "CR", "CodeRabbit"),
  jira: simpleIcon("jira", "Jr", "Jira"),
  confluence: simpleIcon("confluence", "Cf", "Confluence"),
  git: simpleIcon("git", "Git", "Git"),
  mixpanel: simpleIcon("mixpanel", "Mx", "Mixpanel"),
  webpack: simpleIcon("webpack", "Wp", "Webpack Module Federation"),
  json: simpleIcon("json", "JSON", "JSON"),
};

const aliases = {
  angular: "angular",
  angular17plus: "angular",
  react: "react",
  nx: "nx",
  nxmonorepo: "nx",
  ngrx: "ngrx",
  rxjs: "rxjs",
  ionic: "ionic",
  pwa: "pwa",
  progressivewebapp: "pwa",
  progressivewebapps: "pwa",
  serviceworkers: "pwa",
  serviceworker: "pwa",
  indexeddb: "indexeddb",
  indexdb: "indexeddb",
  localstorage: "localstorage",
  sessionstorage: "sessionstorage",
  javascript: "javascript",
  typescript: "typescript",
  nextjs: "nextjs",
  html5: "html5",
  css3: "css3",
  tailwind: "tailwind",
  tailwindcss: "tailwind",
  materialui: "mui",
  mui: "mui",
  primeng: "primeng",
  bootstrapui: "bootstrap",
  bootstrap: "bootstrap",
  responsivewebdesign: "css3",
  virtualscrolling: "angular",
  frontendperformanceoptimization: "react",
  uxdesign: "figma",
  node: "node",
  nodejs: "node",
  nestjs: "nestjs",
  java: "java",
  j2ee: "java",
  springboot: "springboot",
  tomcat: "tomcat",
  apachetomcat: "tomcat",
  nginx: "nginx",
  rest: "rest",
  restapis: "rest",
  grpc: "grpc",
  graphql: "graphql",
  openapi: "openapi",
  swagger: "swagger",
  swaggerui: "swagger",
  aws: "aws",
  awsec2: "ec2",
  ec2: "ec2",
  s3: "s3",
  cloudfront: "cloudfront",
  amplify: "amplify",
  iam: "iam",
  efs: "efs",
  elasticbeanstalk: "elasticbeanstalk",
  route53: "route53",
  dynamodb: "dynamo",
  dynamo: "dynamo",
  mongodb: "mongo",
  mongo: "mongo",
  postgresql: "postgres",
  postgres: "postgres",
  mysql: "mysql",
  redis: "redis",
  firebase: "firebase",
  supabase: "supabase",
  meanstack: "angular",
  mernstack: "react",
  kubernetes: "kubernetes",
  k8s: "kubernetes",
  docker: "docker",
  kafka: "kafka",
  apachekafka: "kafka",
  awssns: "sns",
  sns: "sns",
  awssqs: "sqs",
  sqs: "sqs",
  microservices: "kubernetes",
  enterprisesaas: "aws",
  multitenantarchitecture: "aws",
  distributedsystems: "kubernetes",
  scalablewebapplications: "aws",
  hashicorpvault: "vault",
  hashicorpvaultapis: "vault",
  vaultapis: "vault",
  oauth: "oauth",
  oauthflows: "oauth",
  auth0: "auth0",
  keycloak: "keycloak",
  rbac: "keycloak",
  slack: "slack",
  microsoftteams: "teams",
  teams: "teams",
  googledrive: "googledrive",
  onedrive: "onedrive",
  microsoftonedrive: "onedrive",
  hubspot: "hubspot",
  pipedrive: "pipedrive",
  github: "github",
  gitlab: "gitlab",
  jenkins: "jenkins",
  githubactions: "githubactions",
  cicd: "githubactions",
  jest: "jest",
  karma: "karma",
  jasmine: "jasmine",
  cypress: "cypress",
  junit: "junit",
  mockito: "mockito",
  chatgpt: "openai",
  chatgptintegration: "openai",
  aiassisteddevelopment: "openai",
  openai: "openai",
  claude: "claude",
  claudecode: "claude",
  codex: "codex",
  openaicodex: "codex",
  replit: "replit",
  copilot: "githubcopilot",
  githubcopilot: "githubcopilot",
  coderabbit: "coderabbit",
  jira: "jira",
  confluence: "confluence",
  git: "git",
  engineeringleadership: "github",
  systemdesign: "kubernetes",
  technicalroadmaps: "jira",
  teamsleadership: "github",
  teamleadership: "github",
  releasesplanning: "githubactions",
  releaseplanning: "githubactions",
  workflowautomation: "json",
  mixpanel: "mixpanel",
  modulefederationmindset: "webpack",
  configschemas: "json",
  openapipostgresqlmixpanelrest: "openapi",
};

export function normalizeTechKey(value = "") {
  return value
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/\+/g, "plus")
    .replace(/[^a-z0-9]+/g, "");
}

export function getTechFallback(value = "") {
  const words = value.match(/[A-Za-z0-9]+/g) ?? [];
  if (!words.length) return "IT";
  if (words.length === 1) return words[0].slice(0, 4);
  return words
    .slice(0, 3)
    .map((word) => word[0])
    .join("")
    .toUpperCase();
}

export function resolveTechLogo(value = "") {
  const direct = techLogos[value];
  if (direct) return { key: value, ...direct };

  const normalized = normalizeTechKey(value);
  const key = aliases[normalized] ?? normalized;
  const logo = techLogos[key];

  if (!logo) return null;
  return { key, ...logo };
}
